name: Build x86 Simple

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
      
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: 'latest'
        vcpkgJsonGlob: 'vcpkg.json'
        vcpkgTriplet: 'x86-windows-static'
        
    - name: Build Solution
      run: |
        msbuild "Installer.sln" /p:Configuration=Release /p:Platform=Win32 /p:VcpkgEnabled=true /p:VcpkgUseStatic=true /p:VcpkgTriplet=x86-windows-static
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: KoronePlayerLauncher-x86
        path: BootstrapperClient\bin\Release\Win32\KoronePlayerLauncher.exe
        retention-days: 7
